version: "3.9"
services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
  client:
    build:
      context: ./client
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "5173:5173"
    restart: unless-stopped
