version: "3.9"
services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
  client:
    build:
      context: ./client
      args:
        - VITE_API_BASE_URL=http://localhost:3000
    environment:
      - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "5173:5173"
    restart: unless-stopped
