name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install server deps
        working-directory: server
        run: |
          npm ci

      - name: Build server
        working-directory: server
        run: |
          npm run build

      - name: Rsync to droplet
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: server/
          remote_path: /var/www/project/server
          remote_host: ${{ secrets.DO_HOST }}
          remote_user: ${{ secrets.DO_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/project/server
            npm ci --omit=dev
            pm2 startOrReload ecosystem.config.js
